ItemEvents.tooltip(event => {
  //绿色字为补充物品的额外用法
  event.add('minecraft:golden_sword', Text.translate('kubejs.tooltip.item.minecraft.golden_sword.0'))
  event.add('chimes:bamboo_chimes', Text.translate('kubejs.tooltip.item.chimes.bamboo_chimes.0'))
  event.add('chimes:iron_chimes', Text.translate('kubejs.tooltip.item.chimes.iron_chimes.0'))
  event.add('chimes:carved_bamboo_chimes', Text.translate('kubejs.tooltip.item.chimes.carved_bamboo_chimes.0'))
  event.add('chimes:copper_chimes', Text.translate('kubejs.tooltip.item.chimes.copper_chimes.0'))
  event.add('chimes:amethyst_chimes', Text.translate('kubejs.tooltip.item.chimes.amethyst_chimes.0'))
  event.add('chimes:glass_bells', Text.translate('kubejs.tooltip.item.chimes.glass_bells.0'))
  event.add('minecraft:anvil', Text.translate('kubejs.tooltip.item.minecraft.anvil.0'))
  event.add('minecraft:damaged_anvil', Text.translate('kubejs.tooltip.item.minecraft.damaged_anvil.0'))
  event.add('minecraft:chipped_anvil', Text.translate('kubejs.tooltip.item.minecraft.chipped_anvil.0'))
  event.add('upgrade_aquatic:boiled_pickerelweed', Text.translate('kubejs.tooltip.item.upgrade_aquatic.boiled_pickerelweed.0'))
  event.add('quark:grate', Text.translate('kubejs.tooltip.item.quark.grate.0'))
  event.add('quark:bottled_cloud', [Text.translate('kubejs.tooltip.item.quark.bottled_cloud.0'), Text.translate('kubejs.tooltip.item.quark.bottled_cloud.1'), Text.translate('kubejs.tooltip.item.quark.bottled_cloud.2')])
  event.add('quark:chute', [Text.translate('kubejs.tooltip.item.quark.chute.0'), Text.translate('kubejs.tooltip.item.quark.chute.1')])
  event.add('quark:feeding_trough', Text.translate('kubejs.tooltip.item.quark.feeding_trough.0'))
  event.add('quark:soul_bead', Text.translate('kubejs.tooltip.item.quark.soul_bead.0'))
  event.add('quark:seed_pouch', [Text.translate('kubejs.tooltip.item.quark.seed_pouch.0'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.1'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.2'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.3'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.4'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.5')])
  event.add('quark:gravisand', Text.translate('kubejs.tooltip.item.quark.gravisand.0'))
  event.add('biomemakeover:altar', Text.translate('kubejs.tooltip.item.biomemakeover.altar.0'))
  event.add('quark:ancient_tome', [Text.translate('kubejs.tooltip.item.quark.ancient_tome.0'), Text.translate('kubejs.tooltip.item.quark.ancient_tome.1'), Text.translate('kubejs.tooltip.item.quark.ancient_tome.2')])
  event.add('biomemakeover:enchanted_totem', Text.translate('kubejs.tooltip.item.biomemakeover.enchanted_totem.0'))
  event.add('biomemakeover:witch_hat', Text.translate('kubejs.tooltip.item.biomemakeover.witch_hat.0'))
  event.add('supplementaries:key', Text.translate('kubejs.tooltip.item.supplementaries.key.0'))
  event.add('supplementaries:flute', [Text.translate('kubejs.tooltip.item.supplementaries.flute.0'), Text.translate('kubejs.tooltip.item.supplementaries.flute.1'), Text.translate('kubejs.tooltip.item.supplementaries.flute.2')])
  event.add('supplementaries:antique_ink', Text.translate('kubejs.tooltip.item.supplementaries.antique_ink.0'))
  event.add('supplementaries:cog_block', Text.translate('kubejs.tooltip.item.supplementaries.cog_block.0'))
  event.add('quark:trowel', Text.translate('kubejs.tooltip.item.quark.trowel.0'))
  event.add('minecraft:torch', Text.translate('kubejs.tooltip.item.minecraft.torch.0'))
  event.add('l2complements:eternium_hoe', Text.translate('kubejs.tooltip.item.l2complements.eternium_hoe.0'))
  event.add('tofucraft:bottle_soyoil', Text.translate('kubejs.tooltip.item.tofucraft.bottle_soyoil.0'))
  //黄色字为作者的个人吐槽
  event.add('minecraft:diorite', [Text.translate('kubejs.tooltip.item.minecraft.diorite.0'), Text.translate('kubejs.tooltip.item.minecraft.diorite.1')])
  event.add('irons_spellbooks:keeper_flamberge', Text.translate('kubejs.tooltip.item.irons_spellbooks.keeper_flamberge.0'))
  event.add('barbequesdelight:burnt_skewer', Text.translate('kubejs.tooltip.item.barbequesdelight.burnt_skewer.0'))
  event.add('etcetera:cotton_flower', Text.translate('kubejs.tooltip.item.etcetera.cotton_flower.0'))
  event.add('etcetera:cotton_seeds', Text.translate('kubejs.tooltip.item.etcetera.cotton_seeds.0'))
  event.add('etcetera:tidal_helmet', Text.translate('kubejs.tooltip.item.etcetera.tidal_helmet.0'))
  event.add('minecraft:iron_helmet', Text.translate('kubejs.tooltip.item.minecraft.iron_helmet.0'))
  event.add('candlelight:cooking_hat', Text.translate('kubejs.tooltip.item.candlelight.cooking_hat.0'))
  event.add('fruitsdelight:bayberry', Text.translate('kubejs.tooltip.item.fruitsdelight.bayberry.0'))
  event.add('fruitsdelight:lychee', Text.translate('kubejs.tooltip.item.fruitsdelight.lychee.0'))
  event.add('fruitsdelight:durian', Text.translate('kubejs.tooltip.item.fruitsdelight.durian.0'))
  event.add('fruitsdelight:baked_durian', Text.translate('kubejs.tooltip.item.fruitsdelight.baked_durian.0'))
  event.add('fruitsdelight:kiwi', Text.translate('kubejs.tooltip.item.fruitsdelight.kiwi.0'))
  event.add('fruitsdelight:peach', Text.translate('kubejs.tooltip.item.fruitsdelight.peach.0'))
  event.add('fruitsdelight:pineapple', Text.translate('kubejs.tooltip.item.fruitsdelight.pineapple.0'))
  event.add('fruitsdelight:lemon', Text.translate('kubejs.tooltip.item.fruitsdelight.lemon.0'))
  event.add('vinery:cherry', [Text.translate('kubejs.tooltip.item.vinery.cherry.0'), Text.translate('kubejs.tooltip.item.vinery.cherry.1')])
  event.add('vintagedelight:kimchi', Text.translate('kubejs.tooltip.item.vintagedelight.kimchi.0'))
  event.add('vintagedelight:century_egg', Text.translate('kubejs.tooltip.item.vintagedelight.century_egg.0'))
  event.add('vintagedelight:pickled_egg', Text.translate('kubejs.tooltip.item.vintagedelight.pickled_egg.0'))
  event.add('vintagedelight:pickle', Text.translate('kubejs.tooltip.item.vintagedelight.pickle.0'))
  event.add('vintagedelight:peanut', Text.translate('kubejs.tooltip.item.vintagedelight.peanut.0'))
  event.add('casualness_delight:fried_fish', Text.translate('kubejs.tooltip.item.casualness_delight.fried_fish.0'))
  event.add('casualness_delight:fish_and_chips', Text.translate('kubejs.tooltip.item.casualness_delight.fish_and_chips.0'))
  event.add('casualness_delight:stargazy_pie', Text.translate('kubejs.tooltip.item.casualness_delight.stargazy_pie.0'))
  event.add('casualness_delight:bobo_chicken', Text.translate('kubejs.tooltip.item.casualness_delight.bobo_chicken.0'))
  event.add('casualness_delight:paper_wrapped_fish', Text.translate('kubejs.tooltip.item.casualness_delight.paper_wrapped_fish.0'))
  event.add('youkaishomecoming:raw_lamprey', Text.translate('kubejs.tooltip.item.youkaishomecoming.raw_lamprey.0'))
  event.add('youkaishomecoming:raw_lamprey_fillet', Text.translate('kubejs.tooltip.item.youkaishomecoming.raw_lamprey_fillet.0'))
  event.add('youkaishomecoming:chest_of_heart_throbbing_surprise', [Text.translate('kubejs.tooltip.item.youkaishomecoming.chest_of_heart_throbbing_surprise.0'), Text.translate('kubejs.tooltip.item.youkaishomecoming.chest_of_heart_throbbing_surprise.1'), Text.translate('kubejs.tooltip.item.youkaishomecoming.chest_of_heart_throbbing_surprise.2')])
  event.add('youkaishomecoming:oily_bean_curd', Text.translate('kubejs.tooltip.item.youkaishomecoming.oily_bean_curd.0'))
  event.add('youkaishomecoming:udumbara_flower', [Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.0'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.1'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.2'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.3'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.4'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.5')])
  event.add('minecraft:cooked_beef', Text.translate('kubejs.tooltip.item.minecraft.cooked_beef.0'))
  event.add('youkaishomecoming:roe', Text.translate('kubejs.tooltip.item.youkaishomecoming.roe.0'))
  event.add('casualness_delight:tonkatsu', Text.translate('kubejs.tooltip.item.casualness_delight.tonkatsu.0'))
  event.add('casualness_delight:raw_fried_dumpling', Text.translate('kubejs.tooltip.item.casualness_delight.raw_fried_dumpling.0'))
  event.add('casualness_delight:fried_dumpling', Text.translate('kubejs.tooltip.item.casualness_delight.fried_dumpling.0'))
  event.add('casualness_delight:fried_chicken_chip', Text.translate('kubejs.tooltip.item.casualness_delight.fried_chicken_chip.0'))
  event.add('fruitsdelight:persimmon', [Text.translate('kubejs.tooltip.item.fruitsdelight.persimmon.0'), Text.translate('kubejs.tooltip.item.fruitsdelight.persimmon.1')])
  event.add('fruitsdelight:cranberry', Text.translate('kubejs.tooltip.item.fruitsdelight.cranberry.0'))
  event.add('casualness_delight:roast_gluten', Text.translate('kubejs.tooltip.item.casualness_delight.roast_gluten.0'))
  event.add('delightful:field_salad', Text.translate('kubejs.tooltip.item.delightful.field_salad.0'))
  event.add('ends_delight:end_mixed_salad', Text.translate('kubejs.tooltip.item.ends_delight.end_mixed_salad.0'))
  event.add('ends_delight:assorted_salad', Text.translate('kubejs.tooltip.item.ends_delight.assorted_salad.0'))
  event.add('farmersdelight:fruit_salad', Text.translate('kubejs.tooltip.item.farmersdelight.fruit_salad.0'))
  event.add('farmersdelight:mixed_salad', Text.translate('kubejs.tooltip.item.farmersdelight.mixed_salad.0'))
  event.add('farmersdelight:nether_salad', Text.translate('kubejs.tooltip.item.farmersdelight.nether_salad.0'))
  event.add('vintagedelight:cucumber_salad', Text.translate('kubejs.tooltip.item.vintagedelight.cucumber_salad.0'))
  event.add('candlelight:salad', Text.translate('kubejs.tooltip.item.candlelight.salad.0'))
  event.add('candlelight:beetroot_salad', Text.translate('kubejs.tooltip.item.candlelight.beetroot_salad.0'))
  event.add('bakeries:baguette', Text.translate('kubejs.tooltip.item.bakeries.baguette.0'))
  event.add('seasonals:mixed_berry_muffin', Text.translate('kubejs.tooltip.item.seasonals.mixed_berry_muffin.0'))
  event.add('seasonals:chocolate_pumpkin_muffin', Text.translate('kubejs.tooltip.item.seasonals.chocolate_pumpkin_muffin.0'))
  event.add('casualness_delight:green_tongue', Text.translate('kubejs.tooltip.item.casualness_delight.green_tongue.0'))
  event.add('casualness_delight:spicy_strips', Text.translate('kubejs.tooltip.item.casualness_delight.spicy_strips.0'))
  event.add('crockpot:avaj', Text.translate('kubejs.tooltip.item.crockpot.avaj.0'))
  event.add('crockpot:bunny_stew', Text.translate('kubejs.tooltip.item.crockpot.bunny_stew.0'))
  event.add('crockpot:tea', Text.translate('kubejs.tooltip.item.crockpot.tea.0'))
  event.add('crockpot:milkmade_hat', Text.translate('kubejs.tooltip.item.crockpot.milkmade_hat.0'))
  event.add('crockpot:creative_milkmade_hat', Text.translate('kubejs.tooltip.item.crockpot.creative_milkmade_hat.0'))
  event.add('crockpot:moqueca', Text.translate('kubejs.tooltip.item.crockpot.moqueca.0'))
  event.add('crockpot:meat_balls', Text.translate('kubejs.tooltip.item.crockpot.meat_balls.0'))
  event.add('crockpot:gnaws_coin', Text.translate('kubejs.tooltip.item.crockpot.gnaws_coin.0'))
  event.add('artifacts:everlasting_beef', [Text.translate('kubejs.tooltip.item.artifacts.everlasting_beef.0'), Text.translate('kubejs.tooltip.item.artifacts.everlasting_beef.1')])
  event.add('artifacts:eternal_steak', [Text.translate('kubejs.tooltip.item.artifacts.eternal_steak.0'), Text.translate('kubejs.tooltip.item.artifacts.eternal_steak.1')])
  event.add('youkaishomecoming:green_coffee_bean', Text.translate('kubejs.tooltip.item.youkaishomecoming.green_coffee_bean.0'))
  event.add('youkaishomecoming:coffee_beans', Text.translate('kubejs.tooltip.item.youkaishomecoming.coffee_beans.0'))
  event.add('youkaishomecoming:coffee_powder', Text.translate('kubejs.tooltip.item.youkaishomecoming.coffee_powder.0'))
  event.add('bakeries:raw_coffee_bean', Text.translate('kubejs.tooltip.item.bakeries.raw_coffee_bean.0'))
  event.add('bakeries:coffee_bean', Text.translate('kubejs.tooltip.item.bakeries.coffee_bean.0'))
  event.add('bakeries:ground_coffee', Text.translate('kubejs.tooltip.item.bakeries.ground_coffee.0'))
  //为标签添加的物品吐槽
  event.add('#forge:pasta', Text.translate('kubejs.tooltip.tag.forge.pasta.0'))
  event.add('#forge:chocolate', Text.translate('kubejs.tooltip.tag.forge.chocolate.0'))
  event.add('#forge:fruits/passion_fruit', Text.translate('kubejs.tooltip.tag.forge.fruits.passion_fruit.0'))
  event.add('#forge:fruits/raspberries', Text.translate('kubejs.tooltip.tag.forge.fruits.raspberries.0'))
  event.add('#forge:fruits/lemon', Text.translate('kubejs.tooltip.tag.forge.fruits.lemon.0'))
  event.add('#forge:fruits/blueberry', Text.translate('kubejs.tooltip.tag.forge.fruits.blueberry.0'))
  event.add('#forge:fruits/mango', Text.translate('kubejs.tooltip.tag.forge.fruits.mango.0'))
  event.add('#forge:fruits/peach', Text.translate('kubejs.tooltip.tag.forge.fruits.peach.0'))
  event.add('#forge:fruits/pineapple', Text.translate('kubejs.tooltip.tag.forge.fruits.pineapple.0'))
  event.add('#forge:fruits/cranberry', Text.translate('kubejs.tooltip.tag.forge.fruits.cranberry.0'))
  event.add('#forge:fruits/orange', Text.translate('kubejs.tooltip.tag.forge.fruits.orange.0'))
  event.add('#forge:fruits/lychee', Text.translate('kubejs.tooltip.tag.forge.fruits.lychee.0'))
  event.add('#forge:fruits/strawberry', Text.translate('kubejs.tooltip.tag.forge.fruits.strawberry.0'))
  event.add('#forge:fruits/hamimelon', Text.translate('kubejs.tooltip.tag.forge.fruits.hamimelon.0'))
  event.add('#forge:fruits/grapes', Text.translate('kubejs.tooltip.tag.forge.fruits.grapes.0'))
  event.add('#forge:fruits/persimmon', Text.translate('kubejs.tooltip.tag.forge.fruits.persimmon.0'))
  event.add('#forge:fruits/watermelon', Text.translate('kubejs.tooltip.tag.forge.fruits.watermelon.0'))
  event.add('#forge:fruits/coconut', Text.translate('kubejs.tooltip.tag.forge.fruits.coconut.0'))
  event.add('#forge:vegetables/onion', Text.translate('kubejs.tooltip.tag.forge.vegetables.onion.0'))
  event.add('#forge:vegetables/tomato', Text.translate('kubejs.tooltip.tag.forge.vegetables.tomato.0'))
  event.add('#forge:vegetables/chili_pepper', Text.translate('kubejs.tooltip.tag.forge.vegetables.chili_pepper.0'))
  event.add('#forge:crops/olives', Text.translate('kubejs.tooltip.tag.forge.crops.olives.0'))
  event.add('#forge:crops/adzuki', Text.translate('kubejs.tooltip.tag.forge.crops.adzuki.0'))
  event.add('#forge:crops/corn', Text.translate('kubejs.tooltip.tag.forge.crops.corn.0'))
  event.add('#forge:crops/dragon_fruit', Text.translate('kubejs.tooltip.tag.forge.crops.dragon_fruit.0'))
  event.add('#forge:crops/apple', Text.translate('kubejs.tooltip.tag.forge.crops.apple.0'))
  event.add('#forge:crops/yucca', Text.translate('kubejs.tooltip.tag.forge.crops.yucca.0'))
  event.add('#forge:crops/currant', Text.translate('kubejs.tooltip.tag.forge.crops.currant.0'))
  event.add('#forge:crops/hawberry', Text.translate('kubejs.tooltip.tag.forge.crops.hawberry.0'))
  event.add('#forge:crops/pear', Text.translate('kubejs.tooltip.tag.forge.crops.pear.0'))
  event.add('#forge:crops/rice', Text.translate('kubejs.tooltip.tag.forge.crops.rice.0'))
  event.add('#forge:crops/mint', Text.translate('kubejs.tooltip.tag.forge.crops.mint.0'))
  event.add('#forge:crops/aloe', Text.translate('kubejs.tooltip.tag.forge.crops.aloe.0'))
  event.add('#forge:crops/carrot', Text.translate('kubejs.tooltip.tag.forge.crops.carrot.0'))
  event.add('#forge:crops/potato', Text.translate('kubejs.tooltip.tag.forge.crops.potato.0'))
  event.add('#forge:crops/beetroot', Text.translate('kubejs.tooltip.tag.forge.crops.beetroot.0'))
  event.add('#forge:crops/leek', Text.translate('kubejs.tooltip.tag.forge.crops.leek.0'))
  event.add('#forge:crops/peanut', Text.translate('kubejs.tooltip.tag.forge.crops.peanut.0'))
  event.add('#forge:crops/cabbage', Text.translate('kubejs.tooltip.tag.forge.crops.cabbage.0'))
  event.add('#forge:crops/cucumber', Text.translate('kubejs.tooltip.tag.forge.crops.cucumber.0'))
  event.add('#forge:crops/barley', Text.translate('kubejs.tooltip.tag.forge.crops.barley.0'))
  event.add('#forge:crops/oat', Text.translate('kubejs.tooltip.tag.forge.crops.oat.0'))
  // Majobroom
  event.add('majobroom:broom', [Text.translate('kubejs.tooltip.item.majobroom.broom.0'), Text.translate('kubejs.tooltip.item.majobroom.broom.1')])
  event.add('majobroom:majo_hat', Text.translate('kubejs.tooltip.item.majobroom.majo_hat.0'))
  event.add('majobroom:majo_cloth', Text.translate('kubejs.tooltip.item.majobroom.majo_cloth.0'))
  event.add('majobroom:majo_stocking', Text.translate('kubejs.tooltip.item.majobroom.majo_stocking.0'))
  event.add('majobroom:majo_boots', Text.translate('kubejs.tooltip.item.majobroom.majo_boots.0'))
  //红色字为禁用物品或危险物品的提示讯息
  event.add('minecraft:enchanting_table', [Text.translate('kubejs.tooltip.item.minecraft.enchanting_table.0'), Text.translate('kubejs.tooltip.item.minecraft.enchanting_table.1')])
  event.add('l2complements:diffusion_wand', Text.translate('kubejs.tooltip.item.l2complements.diffusion_wand.0'))
  event.add('create_sa:block_picker', Text.translate('kubejs.tooltip.item.create_sa.block_picker.0'))
  //event.add('quark:pickarang', Text.translate('kubejs.tooltip.item.quark.pickarang.0'))
  //event.add('quark:flamerang', Text.translate('kubejs.tooltip.item.quark.flamerang.0'))
  // Eggs
  //event.add('create:crushing_wheel', Text.translate('kubejs.tooltip.item.create.crushing_wheel.0'))
})