lockfile_path=pakku-lock.json
server_dir=server
serverpack_dir=build/serverpack
pakku_url=https://github.com/juraj-hrivnak/Pakku/releases/download/v1.4.0/pakku.jar
forge_installer_url_template=https://maven.minecraftforge.net/net/minecraftforge/forge/{mc_version}-{loader_version}/forge-{mc_version}-{loader_version}-installer.jar
neoforge_installer_url_template=https://maven.neoforged.net/releases/net/neoforged/neoforge/{loader_version}/neoforge-{loader_version}-installer.jar
fabric_installer_version=1.0.3
fabric_installer_url_template=https://maven.fabricmc.net/net/fabricmc/fabric-installer/{installer_version}/fabric-installer-{installer_version}.jar
